[book]
language = "uk"
multilingual = false
src = "docs"

# Замініть авторство проєкта на своє
authors = ["Dmytro Shevchenko"]

# Змініть назву проєкта на свою
title = "Система аналізу медіа-контенту"

[preprocessor.plantuml]
plantuml-cmd = "http://www.plantuml.com/plantuml"
use-data-uris = true
